/**
 *  AUTOGENERATED FILE
 *
 * Generated by: Python build script
 * Template:     /builder/templates/Resource.cpp.template
 *
 * Any modifications to this file will be overwritten.
 * Please edit the template instead.
 */

#include "Resource.hpp"
#include <array>

namespace {
    constexpr uint8_t asset_0[] = {
        #embed "C:/Users/firel/source/repos/Loom/assets/fonts/Arimo_Medium.embed.ttf"
    };
    constexpr uint8_t asset_1[] = {
        #embed "C:/Users/firel/source/repos/Loom/assets/fonts/Montserrat-ExtraBold.embed.ttf"
    };
    constexpr uint8_t asset_2[] = {
        #embed "C:/Users/firel/source/repos/Loom/assets/fonts/Montserrat_Medium.embed.ttf"
    };
    constexpr uint8_t asset_3[] = {
        #embed "C:/Users/firel/source/repos/Loom/assets/icons/close.embed.png"
    };

    struct EmbeddedResource {
        uint64_t path_hash;
        const uint8_t* data;
        size_t size;
    };

    constexpr std::array<EmbeddedResource, 4> resources = {{
        {HashedString::computeHash("assets/fonts/Arimo_Medium.ttf"), asset_0, sizeof(asset_0)},
        {HashedString::computeHash("assets/fonts/Montserrat-ExtraBold.ttf"), asset_1, sizeof(asset_1)},
        {HashedString::computeHash("assets/fonts/Montserrat_Medium.ttf"), asset_2, sizeof(asset_2)},
        {HashedString::computeHash("assets/icons/close.png"), asset_3, sizeof(asset_3)},
    }};
}

Resource::Resource(hash::hashed_string hashed_path) {
    for (const auto& entry : resources) {
        if (entry.path_hash == hashed_path.value) {
            m_size = entry.size;
            m_data = entry.data;
            return;
        }
    }
}

const uint8_t* Resource::data() const {
    return m_data;
}

size_t Resource::size() const {
    return m_size;
}

std::string_view Resource::str() const {
    return std::string_view(reinterpret_cast<const char*>(m_data), m_size);
}