/**
 *  AUTOGENERATED FILE
 *
 * Generated by: Python build script
 * Template:     /builder/templates/Signature.cpp.template
 *
 * Any modifications to this file will be overwritten.
 * Please edit the template instead.
 */

#include "Signatures.hpp"
#include <array>
#include <libhat/scanner.hpp>
#include <sdk/mc/deps/core/string/HashedString.hpp>

namespace {
    using namespace hat::literals;

    constexpr std::array<sigs::EmbeddedSignature, 14> signature_registry = {{
        {"SceneFactory::createHudScreen", HashedString::computeHash("SceneFactory::createHudScreen"), "48 89 5C 24 ? 55 56 57 48 8D 6C 24 ? 48 81 EC ? ? ? ? 48 8B F2 48 8B D9 48 89 55 ? 33 FF 0F 57 C0 0F 11 45 ? 0F 57 C9 0F 11 4D ? 66 0F 6F 05"_sigv, sigs::AddressType{ 0 }},
        {"SceneFactory::createPauseScreen", HashedString::computeHash("SceneFactory::createPauseScreen"), "E8 ? ? ? ? 45 33 C0 48 8B D0 48 8B CF 48 8B C3 FF 15 ? ? ? ? 90 4C 89 74 24"_sigv, sigs::AddressType{ 0 }},
        {"SceneFactory::createDeathScreen", HashedString::computeHash("SceneFactory::createDeathScreen"), "48 89 5C 24 ? 55 56 57 48 81 EC ? ? ? ? 48 8B F2 48 8B D9 48 89 54 24 ? 33 ED 0F 57 C0 0F 11 44 24 ? 0F 57 C9 F3 0F 7F 4C 24 ? B9 ? ? ? ? E8 ? ? ? ? 48 8B C8 48 89 44 24 ? 66 0F 6F 05 ? ? ? ? F3 0F 7F 44 24 ? 0F 10 05 ? ? ? ? 0F 11 00 0F B7 05"_sigv, sigs::AddressType{ 0 }},
        {"ScreenContext::tessellator", HashedString::computeHash("ScreenContext::tessellator"), "48 8B 9A ? ? ? ? C6 44 24 ? ? 41 B9 04 00 00 00 41 B0 01 48 8B CB E8 ? ? ? ? 0F 57 DB"_sigv, sigs::AddressType{ 1 }},
        {"Tessellator::mNextColor", HashedString::computeHash("Tessellator::mNextColor"), "89 86 ? ? ? ? 44 38 36 75 ? C6 86 ? ? ? ? ? 0F 57 DB 0F 57 D2"_sigv, sigs::AddressType{ 1 }},
        {"Tessellator::begin", HashedString::computeHash("Tessellator::begin"), "40 57 48 83 EC ? 80 B9 ? ? ? ? ? 4C 8B D1"_sigv, sigs::AddressType{ 0 }},
        {"Tessellator::vertex", HashedString::computeHash("Tessellator::vertex"), "E8 ? ? ? ? F3 0F 10 4E ? 0F 2F F9"_sigv, sigs::AddressType{ 0 }},
        {"Tessellator::end", HashedString::computeHash("Tessellator::end"), "E8 ? ? ? ? 48 8D 55 ? 49 8B CC E8 ? ? ? ? 48 8D 4D ? E8 ? ? ? ? F3 45 0F 11 65"_sigv, sigs::AddressType{ 0 }},
        {"IClientInstance::getSceneFactory", HashedString::computeHash("IClientInstance::getSceneFactory"), "48 8B 80 ? ? ? ? FF 15 ? ? ? ? 48 8D 54 24 ? 48 8B C8 E8 ? ? ? ? 45 33 C0 48 8B D0 48 8B CF 48 8B C3 FF 15 ? ? ? ? 90 4C 89 74 24"_sigv, sigs::AddressType{ 2 }},
        {"IClientInstance::getClientSceneStack", HashedString::computeHash("IClientInstance::getClientSceneStack"), "48 8B 80 ? ? ? ? FF 15 ? ? ? ? 90 48 8B 78 ? 48 8B 07 48 8B 98 ? ? ? ? 48 8B 06 48 8B CE 48 8B 80 ? ? ? ? FF 15 ? ? ? ? 48 8D 54 24 ? 48 8B C8 E8 ? ? ? ? 45 33 C0 48 8B D0 48 8B CF 48 8B C3 FF 15 ? ? ? ? 90 4C 89 74 24"_sigv, sigs::AddressType{ 2 }},
        {"mce::Mesh::renderMesh", HashedString::computeHash("mce::Mesh::renderMesh"), "48 8B C4 53 56 57 48 81 EC ? ? ? ? 48 8B D9"_sigv, sigs::AddressType{ 0 }},
        {"MeshHelpers::renderMeshImmediately", HashedString::computeHash("MeshHelpers::renderMeshImmediately"), "48 89 5C 24 ? 55 56 57 41 56 41 57 48 81 EC ? ? ? ? 49 8B F1 4D 8B F0 48 8B FA"_sigv, sigs::AddressType{ 0 }},
        {"MinecraftPackets::createPacket", HashedString::computeHash("MinecraftPackets::createPacket"), "48 89 5C 24 ? 48 89 6C 24 ? 48 89 74 24 ? 57 48 83 EC ? 48 8B F9 48 89 4C 24 ? 33 ED 81 FA"_sigv, sigs::AddressType{ 0 }},
        {"ScreenView::setupAndRender", HashedString::computeHash("ScreenView::setupAndRender"), "48 89 5C 24 ? 55 56 57 41 54 41 55 41 56 41 57 48 8D AC 24 ? ? ? ? 48 81 EC ? ? ? ? 0F 29 BC 24 ? ? ? ? 48 8B 05 ? ? ? ? 48 33 C4 48 89 85 ? ? ? ? 4C 8B FA"_sigv, sigs::AddressType{ 0 }},
    }};
}

namespace sigs {
    std::span<const EmbeddedSignature> get_all() noexcept {
        return signature_registry;
    }
}